name: View Update Action
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    name: Update Count and Uniques
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get the resources
        uses: actions/checkout@v3
      - name: Call the github-visitors-counter-action
        uses: taurusni/github-visitors-counter-action@v1
        with:
          repo-token: ${{ secrets.PUBLIC_ACCESS_TOKEN  }}
          excluded-list: |
            onedrive-vercel-index
            Heroku-VPS
            reflare-template
            serverless-dns
            v2ray-heroku
            View-Counter
            VPSwindows-LK
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
